on:
  push:
    branches:
      - "main"
jobs:
  publish-dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: docker-compose up -d
      - run: npm install
      - run: cd dispatch && npm run generate:client && npm install && npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dispatch/package.json
          token: ${{ secrets.NPM_TOKEN }}
  publish-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: docker-compose up -d
      - run: npm install
      - run: cd runner && npm run generate:client && npm install && npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dispatch/package.json
          token: ${{ secrets.NPM_TOKEN }}
